/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salas;


import Programacion.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Altas_Usuarios extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    public Altas_Usuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ayuda_b = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        N_tipo = new javax.swing.JTextField();
        Nuevo_nick = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ID_usuario = new javax.swing.JTextField();
        pintxt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Tipo (1 o 0)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nick");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        Ayuda_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Boton_ayuda.png"))); // NOI18N
        Ayuda_b.setToolTipText("Ayuda");
        Ayuda_b.setBorder(null);
        Ayuda_b.setContentAreaFilled(false);
        Ayuda_b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ayuda_b.setFocusPainted(false);
        Ayuda_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayuda_bActionPerformed(evt);
            }
        });
        getContentPane().add(Ayuda_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 40, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Alta de nuevo usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, 70));

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Boton_siguiente.png"))); // NOI18N
        Guardar.setToolTipText("Guardar");
        Guardar.setBorder(null);
        Guardar.setBorderPainted(false);
        Guardar.setContentAreaFilled(false);
        Guardar.setFocusPainted(false);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 50));

        N_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_tipoActionPerformed(evt);
            }
        });
        N_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                N_tipoKeyTyped(evt);
            }
        });
        getContentPane().add(N_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 30));

        Nuevo_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_nickActionPerformed(evt);
            }
        });
        Nuevo_nick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nuevo_nickKeyTyped(evt);
            }
        });
        getContentPane().add(Nuevo_nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFocusPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel4.setText("ID de usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 30));

        ID_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_usuarioActionPerformed(evt);
            }
        });
        ID_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ID_usuarioKeyTyped(evt);
            }
        });
        getContentPane().add(ID_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 40));

        pintxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pintxtKeyTyped(evt);
            }
        });
        getContentPane().add(pintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Fondo_libreta.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void Agregarusuario(){
    String SQL = "insert into n_usuarios(id_usuario,tipo,nick,contra) values (?,?,?,?)";
    String ps = String.valueOf(pintxt.getPassword());
    try {
        PreparedStatement pst = con.prepareStatement(SQL);
        pst.setString(1, ID_usuario.getText());
        pst.setString(2, N_tipo.getText());
        pst.setString(3,Nuevo_nick.getText());
        pst.setString(4, ps);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "registro exisoto");
        PIN p= new PIN();
        p.setVisible(true);
        this.dispose();
        
        
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error de registro\n verifique los datos \n" + e.getMessage());
        this.setVisible(true);
        
    }
}
    
    
    
    
    
    private void Ayuda_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayuda_bActionPerformed
        Ayuda Ventana_ayuda = new Ayuda();
        Ventana_ayuda.setVisible(true);
    }//GEN-LAST:event_Ayuda_bActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
    Agregarusuario();
       
        


    }//GEN-LAST:event_GuardarActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        PIN si = new PIN();
        si.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ExitActionPerformed

    private void N_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_tipoActionPerformed

    private void Nuevo_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_nickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nuevo_nickActionPerformed

    private void ID_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_usuarioActionPerformed

    private void N_tipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_N_tipoKeyTyped
    char Validar = evt.getKeyChar();
        if (Character.isLetter(Validar)) {
            JOptionPane.showMessageDialog(rootPane, "Ingtrese solo numeros");
            
        }
    }//GEN-LAST:event_N_tipoKeyTyped

    private void ID_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_usuarioKeyTyped
        char Validar = evt.getKeyChar();
        if (Character.isLetter(Validar)) {
            JOptionPane.showMessageDialog(rootPane, "Ingtrese solo numeros");
            
        }
    }//GEN-LAST:event_ID_usuarioKeyTyped

    private void Nuevo_nickKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nuevo_nickKeyTyped
         char Validar = evt.getKeyChar();
        if (Character.isDigit(Validar)) {
            JOptionPane.showMessageDialog(rootPane, "Ingtrese solo Letras");
            
        }
    }//GEN-LAST:event_Nuevo_nickKeyTyped

    private void pintxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pintxtKeyTyped
         char Validar = evt.getKeyChar();
        if (Character.isLetter(Validar) ) {
            JOptionPane.showMessageDialog(rootPane, "Ingtrese solo numeros");
            
        }
    }//GEN-LAST:event_pintxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altas_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altas_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altas_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altas_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Altas_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda_b;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField ID_usuario;
    private javax.swing.JTextField N_tipo;
    private javax.swing.JTextField Nuevo_nick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pintxt;
    // End of variables declaration//GEN-END:variables
}
