/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salas;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author HP
 */
public class Inicio extends javax.swing.JFrame {

   
   
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jToolBar1 = new javax.swing.JToolBar();
        Archivo = new javax.swing.JButton();
        Calendario = new javax.swing.JButton();
        Opciones = new javax.swing.JButton();
        Auditorio = new javax.swing.JButton();
        Audiovisual = new javax.swing.JButton();
        Salas_de_computo = new javax.swing.JButton();
        Digital = new javax.swing.JButton();
        Audiovisual_label = new javax.swing.JLabel();
        Auditorio_label = new javax.swing.JLabel();
        Computo_label = new javax.swing.JLabel();
        Digital_Label = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Fondo_Inicio = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Archivo.setText("Archivo");
        Archivo.setToolTipText("abra un nuevo archivo ");
        Archivo.setFocusable(false);
        Archivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Archivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });
        jToolBar1.add(Archivo);

        Calendario.setText("Calendario");
        Calendario.setToolTipText("Consulte el calendario de actividades");
        Calendario.setFocusable(false);
        Calendario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Calendario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalendarioActionPerformed(evt);
            }
        });
        jToolBar1.add(Calendario);

        Opciones.setText("Opciones ");
        Opciones.setToolTipText("Modifique acciones, ingrese otro usuario");
        Opciones.setFocusable(false);
        Opciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Opciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });
        jToolBar1.add(Opciones);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        Auditorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Auditorio2.png"))); // NOI18N
        Auditorio.setToolTipText("Agregue actividad al auditorio");
        Auditorio.setBorder(null);
        Auditorio.setBorderPainted(false);
        Auditorio.setContentAreaFilled(false);
        Auditorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Auditorio.setFocusPainted(false);
        Auditorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuditorioActionPerformed(evt);
            }
        });
        getContentPane().add(Auditorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 120, 90));

        Audiovisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Proyector5.png"))); // NOI18N
        Audiovisual.setToolTipText("Agregue Actividad a la sala Audiovisual");
        Audiovisual.setBorder(null);
        Audiovisual.setBorderPainted(false);
        Audiovisual.setContentAreaFilled(false);
        Audiovisual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Audiovisual.setFocusPainted(false);
        Audiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudiovisualActionPerformed(evt);
            }
        });
        getContentPane().add(Audiovisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 80));

        Salas_de_computo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/ONZ74N03.gif"))); // NOI18N
        Salas_de_computo.setToolTipText("Agregue Actividad a salas de computo");
        Salas_de_computo.setBorderPainted(false);
        Salas_de_computo.setContentAreaFilled(false);
        Salas_de_computo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salas_de_computo.setFocusPainted(false);
        Salas_de_computo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salas_de_computoActionPerformed(evt);
            }
        });
        getContentPane().add(Salas_de_computo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 150, 110));

        Digital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/descarga2.gif"))); // NOI18N
        Digital.setToolTipText("Agregue Actividad al aula digital");
        Digital.setBorderPainted(false);
        Digital.setContentAreaFilled(false);
        Digital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digital.setFocusPainted(false);
        Digital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitalActionPerformed(evt);
            }
        });
        getContentPane().add(Digital, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 140, 90));

        Audiovisual_label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Audiovisual_label.setText("AudioVisual");
        getContentPane().add(Audiovisual_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 100, 40));

        Auditorio_label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Auditorio_label.setText("Auditorio");
        getContentPane().add(Auditorio_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 80, 40));

        Computo_label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Computo_label.setText("Salas de computo");
        getContentPane().add(Computo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 160, 50));

        Digital_Label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Digital_Label.setText("Aula Digital");
        getContentPane().add(Digital_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 100, 40));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        Exit.setToolTipText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFocusPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 50, 30));

        Fondo_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Fondo_libreta.png"))); // NOI18N
        getContentPane().add(Fondo_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void AudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudiovisualActionPerformed
        
               
           RegistroAudiovisual vent = new RegistroAudiovisual();
           vent.setVisible(true);
           this.dispose();
          
        
    }//GEN-LAST:event_AudiovisualActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        dispose();
        PIN pin = new PIN();
        pin.setVisible(true);

    }//GEN-LAST:event_ExitActionPerformed

    private void AuditorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuditorioActionPerformed
       RegistrosAuditorio VAU = new RegistrosAuditorio();
       VAU.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_AuditorioActionPerformed

    private void DigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitalActionPerformed
        RegistroAulaDigital VD= new RegistroAulaDigital();
       VD.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_DigitalActionPerformed

    private void Salas_de_computoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salas_de_computoActionPerformed
        Salas_Computo vent = new Salas_Computo();
        vent.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_Salas_de_computoActionPerformed

    private void CalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalendarioActionPerformed
        Calendario nc = new Calendario();
        nc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CalendarioActionPerformed

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
        Opciones nueva= new Opciones();
        nueva.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_OpcionesActionPerformed

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed
        Busqueda_salas1 nueva = new Busqueda_salas1();
        nueva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Archivo;
    private javax.swing.JButton Audiovisual;
    private javax.swing.JLabel Audiovisual_label;
    private javax.swing.JButton Auditorio;
    private javax.swing.JLabel Auditorio_label;
    private javax.swing.JButton Calendario;
    private javax.swing.JLabel Computo_label;
    private javax.swing.JButton Digital;
    private javax.swing.JLabel Digital_Label;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Fondo_Inicio;
    private javax.swing.JButton Opciones;
    private javax.swing.JButton Salas_de_computo;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables


}
