/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salas;

import Programacion.Autoinc;
import Programacion.conexionSQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class N_sala extends javax.swing.JFrame {

   conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    public N_sala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void AgregarSala(){
        Autoinc s= new Autoinc();
        int id = s.autoincsalas();
        
    String SQL = "insert into salas(id_sala,Nombre,Ubicacion,Uso,Capacidad,Inmueble_descripcion,Estado) values (?,?,?,?,?,?,?)";
   if(Estado.isSelected()){
       
   }
    try {
        PreparedStatement pst = con.prepareStatement(SQL);
        pst.setString(1, String.valueOf(id));
        pst.setString(2, N_sala.getText());
        pst.setString(3, Ubicacion.getText());
        pst.setString(4,Uso.getText());
       pst.setString(5,Capacidad.getText());
        pst.setString(6,Descripcion.getText());
         if(Estado.isSelected()){
       pst.setString(7, String.valueOf('1'));
   }else{
             pst.setString(7, String.valueOf('0'));
         }
       
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "registro exisoto");
        Inicio p= new Inicio();
        p.setVisible(true);
        
        
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error de registro\n verifique los datos \n" + e.getMessage());
        N_sala.setText("");
        Ubicacion.setText("");
        Uso.setText("");
        Capacidad.setText("");
        Descripcion.setText("");
        this.setVisible(true);
        
    }
}
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Estado = new javax.swing.JToggleButton();
        Descripcion = new javax.swing.JTextField();
        Capacidad = new javax.swing.JTextField();
        Uso = new javax.swing.JTextField();
        Ubicacion = new javax.swing.JTextField();
        N_sala = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        Validar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre sala:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, -1, -1));

        jLabel2.setText("ubicacion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 63, -1));

        jLabel3.setText("Uso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 34, 19));

        jLabel4.setText("Capacidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        jLabel5.setText("Materiales");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));

        jLabel6.setText("Estado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, 49, 27));

        Estado.setBackground(new java.awt.Color(0, 204, 0));
        Estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadoMouseClicked(evt);
            }
        });
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 60, 40));

        Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 168, 33));

        Capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadActionPerformed(evt);
            }
        });
        getContentPane().add(Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 144, -1));
        getContentPane().add(Uso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 144, -1));
        getContentPane().add(Ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 119, -1));

        N_sala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                N_salaKeyTyped(evt);
            }
        });
        getContentPane().add(N_sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 158, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        Exit.setToolTipText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFocusPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 30));

        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 40));

        Validar.setText("Validar");
        Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarActionPerformed(evt);
            }
        });
        getContentPane().add(Validar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Fondo_libreta.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadActionPerformed

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        dispose();
        Opciones pin = new Opciones();
        pin.setVisible(true);
    }//GEN-LAST:event_ExitActionPerformed

    private void EstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadoMouseClicked
        if (Estado.isSelected()){
            Estado.setBackground(Color.red);
        }else{
            Estado.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_EstadoMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       AgregarSala();
       N_sala.setText("");
        Ubicacion.setText("");
        Uso.setText("");
        Capacidad.setText("");
        Descripcion.setText("");
        Opciones a = new Opciones();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void N_salaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_N_salaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_N_salaKeyTyped

    private void ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarActionPerformed
       if( Validar()==1){
            btnAgregar.setEnabled(true);
       }else{
           btnAgregar.setEnabled(false);
        N_sala.setText("");
        Ubicacion.setText("");
        Uso.setText("");
        Capacidad.setText("");
        Descripcion.setText("");
       }
    }//GEN-LAST:event_ValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_sala().setVisible(true);
            }
        });
    }
    private int Validar(){
        int a=0;
        try {
            
        
        if (!N_sala.getText().isEmpty()) {
            
            if(!Ubicacion.getText().isEmpty()){
               
             if(!Uso.getText().isEmpty()){
                 
                 if(!Capacidad.getText().isEmpty()){
                    
                     if(!Descripcion.getText().isEmpty()){
                         a=1;
                     }else{
                         JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                         btnAgregar.setEnabled(false);
                         a=0;
                     }
                 }else{
                     JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                     btnAgregar.setEnabled(false);
                     a=0;
                 }
             } else{
                 JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                      btnAgregar.setEnabled(false);
                                      a=0;

             }  
            }else{
               JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes"); 
                                    btnAgregar.setEnabled(false);
                                     a=0;

            }
        } else {
            JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes");
                                 btnAgregar.setEnabled(false);
                                  a=0;

        }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "error \t "+ e.getMessage());
        }
        return a;
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Capacidad;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JToggleButton Estado;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField N_sala;
    private javax.swing.JTextField Ubicacion;
    private javax.swing.JTextField Uso;
    private javax.swing.JButton Validar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
