/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salas;

import Programacion.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PIN extends javax.swing.JFrame {

 conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    public PIN() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_propio = new javax.swing.JLabel();
        Logo_uni = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        Cabezas = new javax.swing.JLabel();
        Ingrese = new javax.swing.JLabel();
        Ayuda_b = new javax.swing.JButton();
        Config_b = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        U_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();
        txtpin = new javax.swing.JPasswordField();
        Fondo_blanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_propio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Lgo_equipo.2png.png"))); // NOI18N
        getContentPane().add(Logo_propio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 97));

        Logo_uni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Logo_uni.png"))); // NOI18N
        getContentPane().add(Logo_uni, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 32, 120, -1));

        Bienvenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Bienvenido.png"))); // NOI18N
        getContentPane().add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 32, -1, 97));

        Cabezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Cabezas icono.png"))); // NOI18N
        getContentPane().add(Cabezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 167, -1, -1));

        Ingrese.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Ingrese.setText(" Pin: ");
        getContentPane().add(Ingrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 75, 49));

        Ayuda_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Boton_ayuda.png"))); // NOI18N
        Ayuda_b.setToolTipText("Ayuda");
        Ayuda_b.setBorder(null);
        Ayuda_b.setContentAreaFilled(false);
        Ayuda_b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ayuda_b.setFocusPainted(false);
        Ayuda_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayuda_bActionPerformed(evt);
            }
        });
        getContentPane().add(Ayuda_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 60, 50));

        Config_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Boton_Configuracion.png"))); // NOI18N
        Config_b.setToolTipText("Agregue otro NIP");
        Config_b.setBorder(null);
        Config_b.setBorderPainted(false);
        Config_b.setContentAreaFilled(false);
        Config_b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Config_b.setFocusPainted(false);
        Config_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Config_bActionPerformed(evt);
            }
        });
        getContentPane().add(Config_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 70, 50));

        Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Boton_siguiente.png"))); // NOI18N
        Aceptar.setToolTipText("Aceptar");
        Aceptar.setBorder(null);
        Aceptar.setBorderPainted(false);
        Aceptar.setContentAreaFilled(false);
        Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Aceptar.setEnabled(false);
        Aceptar.setFocusPainted(false);
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 60, 60));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        Exit.setToolTipText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFocusPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 50, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Nick:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 90, 30));

        U_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_nombreActionPerformed(evt);
            }
        });
        U_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                U_nombreKeyPressed(evt);
            }
        });
        getContentPane().add(U_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Tipo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 50, 30));

        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 60, 30));

        txtpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpinKeyPressed(evt);
            }
        });
        getContentPane().add(txtpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 120, 50));

        Fondo_blanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Fondo_libreta.png"))); // NOI18N
        getContentPane().add(Fondo_blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 690, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public int validardatos(){
        int v=0;
        if(!Tipo.getText().isEmpty()){
            if (!U_nombre.getText().isEmpty()) {
               
                    Aceptar.setEnabled(true);
                    v=1;
               
            } else {
                JOptionPane.showMessageDialog(null, "llene todos los campos por favor");
            }
        }else{
            JOptionPane.showMessageDialog(null, "llene todos los campos por favor");
        }
        return v;
    }
    public int validarUsuario(){
        int resultado=0;
        int opc=0;
    String ps = String.valueOf(txtpin.getPassword());
    String usuario=U_nombre.getText();
    String tipo= Tipo.getText();
    
    char comparacion= tipo.charAt(0);
    
    if (comparacion== '1' ){
    String SQL = "select * from n_usuarios where nick= '"+ usuario +"'and contra='"+ps+"'and tipo='"+tipo+ "'";
    try {
        Statement st=con.createStatement();
        ResultSet rs= st.executeQuery(SQL);
        
        if (rs.next()) {
            resultado=1;
           if(resultado==1){
               if(Integer.parseInt(Tipo.getText())==1){
               Inicio in = new Inicio();
               in.setVisible(true);
               this.dispose();
               }else{
                   Busqueda_salas0 c= new Busqueda_salas0();
                   c.setVisible(true);
                   this.dispose();
               }
           } 
            
        }else{
            JOptionPane.showMessageDialog(null, "Error de acceso, verifique los datos \n este usuario no esta registrado");
        }
        
        
        
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, "Error de acceso, verifique los datos"+e.getMessage());
       PIN inu= new PIN();
       inu.setVisible(true);
        
             }
    
        }else{
         String SQL = "select * from n_usuarios where nick = '"+ usuario +"'and contra='"+ps+"'and tipo='"+tipo+ "'";
    try {
        Statement st=con.createStatement();
        ResultSet rs= st.executeQuery(SQL);
        
        if (rs.next()) {
            resultado=1;
           if(resultado==1){
               Busqueda_salas0 in = new Busqueda_salas0();
               in.setVisible(true);
               this.dispose();
               
           } 
            
        }else{
            JOptionPane.showMessageDialog(null, "Error de acceso, verifique los datos \n este usuario no esta registrado");
        }
        
        
        
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, "Error de acceso, verifique los datos"+e.getMessage());

        
             }
        
    }
    return opc;
    }
    private void Ayuda_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayuda_bActionPerformed
        Ayuda Ventana_ayuda = new Ayuda();
        Ventana_ayuda.setVisible(true);
    }//GEN-LAST:event_Ayuda_bActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        int v=0;
        if (validardatos()==1) {
             validarUsuario();
        }else{
            JOptionPane.showMessageDialog(null, "corrija los datos");
        }
       
    }//GEN-LAST:event_AceptarActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Cerrar si = new Cerrar();
        si.setVisible(true);
        this.dispose();
    
        
    }//GEN-LAST:event_ExitActionPerformed

    private void Config_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Config_bActionPerformed
        OpcionesInicio n = new OpcionesInicio();
        n.setVisible(true);
        
    }//GEN-LAST:event_Config_bActionPerformed

    private void U_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U_nombreActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void U_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_U_nombreKeyPressed
 
    }//GEN-LAST:event_U_nombreKeyPressed

    private void txtpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpinKeyPressed
        validardatos();
    }//GEN-LAST:event_txtpinKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Ayuda_b;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Cabezas;
    private javax.swing.JButton Config_b;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Fondo_blanco;
    private javax.swing.JLabel Ingrese;
    private javax.swing.JLabel Logo_propio;
    private javax.swing.JLabel Logo_uni;
    private javax.swing.JTextField Tipo;
    private javax.swing.JTextField U_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtpin;
    // End of variables declaration//GEN-END:variables
}
