/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salas;

/**
 *
 * @author HP
 */
public class Salas_Computo extends javax.swing.JFrame {

    /**
     * Creates new form Salas_Computo
     */
    public Salas_Computo() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sala_a_b = new javax.swing.JButton();
        Sala_b_B = new javax.swing.JButton();
        Sala_c_B = new javax.swing.JButton();
        Sala_A = new javax.swing.JLabel();
        Sala_C = new javax.swing.JLabel();
        Sala_B = new javax.swing.JLabel();
        Mensaje_compu = new javax.swing.JLabel();
        Ayuda_b = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sala_a_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/ONZ74N03.gif"))); // NOI18N
        Sala_a_b.setBorder(null);
        Sala_a_b.setBorderPainted(false);
        Sala_a_b.setContentAreaFilled(false);
        Sala_a_b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sala_a_b.setFocusPainted(false);
        Sala_a_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sala_a_bActionPerformed(evt);
            }
        });
        getContentPane().add(Sala_a_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, 110));

        Sala_b_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/ONZ74N03.gif"))); // NOI18N
        Sala_b_B.setBorder(null);
        Sala_b_B.setBorderPainted(false);
        Sala_b_B.setContentAreaFilled(false);
        Sala_b_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sala_b_B.setFocusPainted(false);
        Sala_b_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sala_b_BActionPerformed(evt);
            }
        });
        getContentPane().add(Sala_b_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 150, 110));

        Sala_c_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/ONZ74N03.gif"))); // NOI18N
        Sala_c_B.setBorder(null);
        Sala_c_B.setBorderPainted(false);
        Sala_c_B.setContentAreaFilled(false);
        Sala_c_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sala_c_B.setFocusPainted(false);
        Sala_c_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sala_c_BActionPerformed(evt);
            }
        });
        getContentPane().add(Sala_c_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 150, 110));

        Sala_A.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Sala_A.setText("Sala A ");
        getContentPane().add(Sala_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 60, 60));

        Sala_C.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Sala_C.setText("Sala C");
        getContentPane().add(Sala_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        Sala_B.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Sala_B.setText("Sala B");
        getContentPane().add(Sala_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        Mensaje_compu.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Mensaje_compu.setText("Elija una");
        getContentPane().add(Mensaje_compu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 110, 50));

        Ayuda_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Boton_ayuda.png"))); // NOI18N
        Ayuda_b.setToolTipText("Ayuda");
        Ayuda_b.setBorder(null);
        Ayuda_b.setContentAreaFilled(false);
        Ayuda_b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ayuda_b.setFocusPainted(false);
        Ayuda_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayuda_bActionPerformed(evt);
            }
        });
        getContentPane().add(Ayuda_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 50, 40));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        Exit.setToolTipText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFocusPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Fondo_libreta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

      
        Inicio inc = new Inicio();
        inc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Sala_a_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sala_a_bActionPerformed
         RegistrosComputoA Sa = new RegistrosComputoA();
       Sa.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Sala_a_bActionPerformed

    private void Sala_b_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sala_b_BActionPerformed
       RegistrosComputoB Sb = new RegistrosComputoB();
       Sb.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Sala_b_BActionPerformed

    private void Sala_c_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sala_c_BActionPerformed
        RegistrosComputoC Sc = new RegistrosComputoC();
       Sc.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Sala_c_BActionPerformed

    private void Ayuda_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayuda_bActionPerformed
        Ayuda Ventana_ayuda = new Ayuda();
        Ventana_ayuda.setVisible(true);
    }//GEN-LAST:event_Ayuda_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salas_Computo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salas_Computo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salas_Computo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salas_Computo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salas_Computo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda_b;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Mensaje_compu;
    private javax.swing.JLabel Sala_A;
    private javax.swing.JLabel Sala_B;
    private javax.swing.JLabel Sala_C;
    private javax.swing.JButton Sala_a_b;
    private javax.swing.JButton Sala_b_B;
    private javax.swing.JButton Sala_c_B;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
