/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salas;

import Programacion.conexionSQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Validacion extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    public Validacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        U_nombre = new javax.swing.JTextField();
        Ingrese = new javax.swing.JLabel();
        Pin = new javax.swing.JPasswordField();
        Siguiente_validacion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 30));

        U_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(U_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, 40));

        Ingrese.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Ingrese.setText(" Pin: ");
        getContentPane().add(Ingrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 75, 49));
        getContentPane().add(Pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 111, 49));

        Siguiente_validacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Boton_siguiente.png"))); // NOI18N
        Siguiente_validacion.setBorder(null);
        Siguiente_validacion.setBorderPainted(false);
        Siguiente_validacion.setContentAreaFilled(false);
        Siguiente_validacion.setFocusPainted(false);
        Siguiente_validacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Siguiente_validacionActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente_validacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 60, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Valide sus datos ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, 50));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        Exit.setToolTipText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFocusPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Fondo_libreta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void validarUsuario(){
        int resultado=0;
        
    String ps = String.valueOf(Pin.getPassword());
    String usuario=U_nombre.getText();
   
    String SQL = "select * from Usuarios where u_nombre= '"+ usuario +"'and nip='"+ps+"'";
    try {
        Statement st=con.createStatement();
        ResultSet rs= st.executeQuery(SQL);
        
        if (rs.next()) {
            resultado=1;
           if(resultado==1){
               Altas_Usuarios in = new Altas_Usuarios();
               in.setVisible(true);
               this.dispose();
               
           } 
            
        }else{
            JOptionPane.showMessageDialog(null, "Error de acceso, verifique los datos \n este usuario no esta registrado");
        }
        
        
        
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, "Error de acceso, verifique los datos"+e.getMessage());
       PIN inu= new PIN();
       inu.setVisible(true);
        
    }
    }
    private void U_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U_nombreActionPerformed

    private void Siguiente_validacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Siguiente_validacionActionPerformed
       validarUsuario();
    }//GEN-LAST:event_Siguiente_validacionActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        dispose();
        PIN pin = new PIN();
        pin.setVisible(true);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Ingrese;
    private javax.swing.JPasswordField Pin;
    private javax.swing.JButton Siguiente_validacion;
    private javax.swing.JTextField U_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
